$("#form-bio").click(function(){
    $("#form-bio-body").removeClass("hide");
    $("#form-eap-body").addClass("hide");
    $("#form-ek-body").addClass("hide");
    $("#form-pi-body").addClass("hide");
    $("#form-sar-body").addClass("hide");
    $("#form-daf-body").addClass("hide");
    $("#form-bio-div").addClass("mrf-active");
    $("#form-eap-div").removeClass("mrf-active");
    $("#form-ek-div").removeClass("mrf-active");
    $("#form-pi-div").removeClass("mrf-active");
    $("#form-sar-div").removeClass("mrf-active");
    $("#form-daf-div").removeClass("mrf-active");
  });

  $("#form-eap").click(function(){
    $("#form-eap-body").removeClass("hide");
    $("#form-bio-body").addClass("hide");
    $("#form-ek-body").addClass("hide");
    $("#form-pi-body").addClass("hide");
    $("#form-sar-body").addClass("hide");
    $("#form-daf-body").addClass("hide");
    $("#form-eap-div").addClass("mrf-active");
    $("#form-bio-div").removeClass("mrf-active");
    $("#form-ek-div").removeClass("mrf-active");
    $("#form-pi-div").removeClass("mrf-active");
    $("#form-sar-div").removeClass("mrf-active");
    $("#form-daf-div").removeClass("mrf-active");
  });

  $("#form-ek").click(function(){
    $("#form-ek-body").removeClass("hide");
    $("#form-bio-body").addClass("hide");
    $("#form-eap-body").addClass("hide");
    $("#form-pi-body").addClass("hide");
    $("#form-sar-body").addClass("hide");
    $("#form-daf-body").addClass("hide");
    $("#form-ek-div").addClass("mrf-active");
    $("#form-bio-div").removeClass("mrf-active");
    $("#form-eap-div").removeClass("mrf-active");
    $("#form-pi-div").removeClass("mrf-active");
    $("#form-sar-div").removeClass("mrf-active");
    $("#form-daf-div").removeClass("mrf-active");
  });

  $("#form-pi").click(function(){
    $("#form-pi-body").removeClass("hide");
    $("#form-bio-body").addClass("hide");
    $("#form-ek-body").addClass("hide");
    $("#form-eap-body").addClass("hide");
    $("#form-sar-body").addClass("hide");
    $("#form-daf-body").addClass("hide");
    $("#form-pi-div").addClass("mrf-active");
    $("#form-bio-div").removeClass("mrf-active");
    $("#form-ek-div").removeClass("mrf-active");
    $("#form-eap-div").removeClass("mrf-active");
    $("#form-sar-div").removeClass("mrf-active");
    $("#form-daf-div").removeClass("mrf-active");
  });

  $("#form-sar").click(function(){
    $("#form-sar-body").removeClass("hide");
    $("#form-bio-body").addClass("hide");
    $("#form-ek-body").addClass("hide");
    $("#form-pi-body").addClass("hide");
    $("#form-eap-body").addClass("hide");
    $("#form-sar-div").addClass("mrf-active");
    $("#form-bio-div").removeClass("mrf-active");
    $("#form-ek-div").removeClass("mrf-active");
    $("#form-pi-div").removeClass("mrf-active");
    $("#form-eap-div").removeClass("mrf-active");
  });

  $("#form-daf").click(function(){
    $("#form-daf-body").removeClass("hide");
    $("#form-bio-body").addClass("hide");
    $("#form-ek-body").addClass("hide");
    $("#form-pi-body").addClass("hide");
    $("#form-eap-body").addClass("hide");
    $("#form-daf-div").addClass("mrf-active");
    $("#form-bio-div").removeClass("mrf-active");
    $("#form-ek-div").removeClass("mrf-active");
    $("#form-pi-div").removeClass("mrf-active");
    $("#form-eap-div").removeClass("mrf-active");
  });